---
# module: rd-ansible-browser-linux/tasks/configure
# description: Configure rd-ansible-browser-linux

- name: Create disable screen turn off script
  copy:
    content: |
      #!/bin/sh
      sleep {{ sleep_between_commands }}

      # By default we disable screensaver and screen off options here
      {% for lines in script_lines %}
      {{ lines }}
      {% endfor %}

      # Set resolution and where the monitors sit
      {% for lines in xrandr_lines %}
      {{ lines }}
      {% endfor %}
      sleep {{ sleep_between_commands }}

      # Load midori browsers with specified urls and options
      {% for window in web_windows %}
      midori -e custom-title={{ window['wmctrl_identifier'] }} -e show-navigationbar=false {% if window['fullscreen'] %}-e Fullscreen {% endif %}{% if window['reload'] %}-i {{ window['reload'] }} {% endif %}-a {{ window['url'] }} &
      {% endfor %}

      #wmctrl -l - to get names of windows
      {% for window in web_windows %}
      until $(wmctrl -l | grep -q {{ window['wmctrl_identifier'] }} )
      do
        echo 'Cannot find {{ window['wmctrl_identifier'] }} waiting'
        sleep 1
      done
      wmctrl -r '{{ window['wmctrl_identifier'] }}' -e 0,{{ window['position'] }}
      {% endfor %}
    dest: "{{ autorun_script_path }}"
    mode: a+x
  notify: reboot
