---
# module: rd-ansible-browser-linux/tasks/configure
# description: Configure rd-ansible-browser-linux

- name: Create browser window script
  copy:
    content: |
      #!/bin/sh
      sleep {{ sleep_between_commands }}

      # By default we disable screensaver and screen off options here
      {% for lines in script_lines %}
      {{ lines }}
      {% endfor %}

      # Set resolution and where the monitors sit
      {% for lines in xrandr_lines %}
      {{ lines }}
      {% endfor %}
      sleep {{ sleep_between_commands }}

      # Load browsers with specified urls and options
      {% for window in web_windows %}
      chromium-browser --no-sandbox --test-type {% if window['fullscreen'] %}--start-fullscreen {% endif %}{% if window['reload'] %}--enable-offline-auto-reload {% endif %}-app='{{ window['url'] }}' &
      # --ignore-certificate-errors can be used here if you want to ignore SSL warnings
      {% endfor %}

      #wmctrl -l - to get names of windows
      {% for window in web_windows %}
      until $(wmctrl -l | grep -q '{{ window['wmctrl_identifier'] }}' )
      do
        echo 'Cannot find {{ window['wmctrl_identifier'] }} waiting'
        sleep 1
      done
      wmctrl -r '{{ window['wmctrl_identifier'] }}' -e 0,{{ window['position'] }}
      {% endfor %}
    dest: "{{ autorun_script_path }}"
    mode: a+x
  notify: reboot
