---
# module: rd-ansible-browser-linux/tasks/install
# description: Install our required packages for rd-ansible-browser-linux

- name: Install basic GUI
  apt:
    name: lubuntu-core
    state: present
    install_recommends: no

- name: Install x11 utils
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ packages }}"
  notify: reboot

- name: Autologin
  copy:
    content: |
      [SeatDefaults]
      autologin-user={{ autologin_user }}
      autologin-user-timeout=0
      user-session=Lubuntu
      greeter-session=lightdm-gtk-greeter
    dest: /etc/lightdm/lightdm.conf
  notify: reboot

- name: Line to autorun script
  copy:
    content: |
      @{{ autorun_script_path }}
    dest: /etc/xdg/lxsession/Lubuntu/autostart
  notify: reboot

- name: Overwrite defaults for Lubuntu to hide the task panel
  lineinfile:
    path: /etc/xdg/lxpanel/default/panels/panel
    regexp: "{{ item.regexp }}"
    insertafter: "{{ item.after }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^\s+autohide=', line: '    autohide=1', after: '^\s+backgroundfile' }
    - { regexp: '^\s+heightwhenhidden=', line: '    heightwhenhidden=0', after: '^\s+autohide=' }
  register: create_panel_profile
  notify: reboot

- name: Get home folder of defined user
  shell: "eval echo ~{{ autologin_user }}"
  changed_when: false
  register: user_path
  when: create_panel_profile.changed

- name: Create panel directory
  file:
    path: "{{ user_path.stdout }}/.config/lxpanel/Lubuntu/panels/"
    owner: "{{ autologin_user }}"
    recurse: yes
  when: create_panel_profile.changed
  notify: reboot

- name: Copy new default to user panel
  command: "cp -f /etc/xdg/lxpanel/default/panels/panel {{ user_path.stdout }}/.config/lxpanel/Lubuntu/panels/panel"
  args:
    warn: false
  when: create_panel_profile.changed
  notify: reboot
